### PR TITLE
addition of more worlds Add files via upload

### PR DESCRIPTION
**Pull request by donnerkebab1730**
i hope i have done this right

i know its messy but i dont know how to fix that

also any older mcpe world will work on mcpi

### CODE REVIEW

**Comment by donnerkebab1730** [comment]
wow the typo is real...

**Comment by Alvarito050506** [comment]
Looks good, thanks!

**Comment by Alvarito050506** [comment]
I'll just make some naming changes.

**Comment by donnerkebab1730** [comment]
oki

**Comment by donnerkebab1730** [comment]
yey

**Pull request merged**
