### PR TITLE
FIxed JSON files

### PR DESCRIPTION
**Pull request by leha-code**

### CODE REVIEW

**Comment by leha-code** [comment]
sooo, idk just added the seeds for the mcpi-repo python API I am working on...

**Comment by Luminoso-256** [comment]
Nothing looks terribly off to me. Has this been tested?

**Comment by leha-code** [comment]
Not yet tested. Ill test tomorrow or anyone cn test? Sorry im agan on my ebook

**Review by mobilegmYT — APPROVED** [review]

**Comment by mobilegmYT** [comment]
It looks like this is all just different JSON files, and there isn't added code so I think a merge wouldn't hurt.

**Comment by leha-code** [comment]
Thanks

**Comment by leha-code** [comment]
I won't add code In this repo. There will be another repo for the API

sent from not an computer

**Pull request merged**
