### PR TITLE
Added Fortress world & moved contributions into standard per-folder structure

### PR DESCRIPTION
**Pull request by cwksimon5847**
Author: TheBoyLeastLikelyTo#4375

### CODE REVIEW

**Comment by mobilegmYT** [comment]
Sure, could you just edit worlds/README.md and add a description of the map following the format

**Comment by cwksimon5847** [comment]
@mobilegmYT
Changes made.
I will do the same for my other world contributions.

**Comment by cwksimon5847** [comment]
- Added and updated README.md files for each of my contributions
- Re-added the MCPIW files for each world into the corresponding folder
- Removed original world uploads, previously located at mcpi-repo/worlds/*

**Comment by Alvarito050506** [comment]
Looks good, if @mobilegmYT doesn't have anything else to say, we could merge it.

**Pull request merged**
